# Generated by Django 3.2.8 on 2021-10-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_price', models.IntegerField()),
                ('item_date', models.DateTimeField(verbose_name='date published')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.category')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=20)),
                ('option_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='date published')),
                ('order_complete', models.BooleanField()),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.customer')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.item')),
                ('order_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.option')),
            ],
        ),
    ]
